spring.application.name=SB-EMS

#Embedded Tomcat Port Number
server.port = 5529

#Database Connection Properties
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=Abhiram@007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Application Properties
ems.save.success="SUCCESS : Employee Object Saved"
ems.update.success="SUCCESS : Employee Object Updated"
ems.delete.success="SUCCESS : Employee Object Deleted"

#Application Error Properties
ems.invalid.employee-details="FAILED : Invalid Employee Object"
ems.invalid.employee-notfound="FAILED : Employee Not Found"

ems.db.failed="Failed : DB Error"