spring.application.name=SB-DMS-SERVICE

#Embedded Tomcat Port Number
server.port = 2222

#Database Connection Properties
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=Abhiram@007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Application Properties
dms.save.success=SUCCESS : Department Object Saved
dms.update.success=SUCCESS : Department Object Updated
dms.delete.success=SUCCESS : Department Object Deleted

#Application Error Properties
dms.invalid.department-details="FAILED : Invalid Department Object"
dms.invalid.department-notfound="FAILED : Department Not Found"

dms.db.failed=Failed : DB Error

eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true